# Generated by Django 4.0.3 on 2022-05-15 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(max_length=20)),
                ('sub_name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('contact', models.EmailField(max_length=30)),
                ('img', models.ImageField(upload_to='images/')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
                ('sec', models.CharField(max_length=1)),
                ('img', models.ImageField(upload_to='images/')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=1)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attds.subjects')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attd_id', models.IntegerField()),
                ('session_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attds.sessions')),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attds.students')),
            ],
        ),
    ]
