# Generated by Django 4.0.2 on 2022-02-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.IntegerField()),
                ('da', models.CharField(max_length=50)),
            ],
        ),
    ]
