# Generated by Django 4.0.2 on 2022-02-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attd_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
                ('sec', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('contact', models.EmailField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
