# Generated by Django 4.0.2 on 2022-02-16 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attds', '0002_attendance_sessions_students_teachers_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attds.sessions'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attds.students'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='teacher_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attds.teachers'),
            preserve_default=False,
        ),
    ]
