# Generated by Django 4.0.3 on 2022-05-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attds', '0002_alter_sessions_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='img',
            field=models.ImageField(default='utk.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='img',
            field=models.ImageField(default='tchr.png', upload_to='images/'),
        ),
    ]
