# Generated by Django 4.0.3 on 2022-05-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attds', '0004_alter_students_img_alter_teachers_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='img',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='img',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
    ]
