# Generated by Django 4.0.2 on 2022-02-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attds', '0004_teachers_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
