# Generated by Django 4.0.2 on 2022-02-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attds', '0006_students_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.IntegerField()),
                ('sub_name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='subject_name',
        ),
        migrations.AlterField(
            model_name='sessions',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attds.subjects'),
        ),
    ]
