# Generated by Django 4.0.2 on 2022-02-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attds', '0007_subjects_remove_sessions_dept_remove_sessions_sem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='sub_code',
            field=models.CharField(max_length=20),
        ),
    ]
