# Generated by Django 4.0.2 on 2022-02-22 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attds', '0008_alter_subjects_sub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
