# Generated by Django 4.0.3 on 2022-05-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attds', '0009_alter_sessions_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('allowed_users', models.CharField(max_length=255)),
            ],
        ),
    ]
